const products = [
  {
    id: 1,
    slug: 'midnight-otaku-overshirt',
    name: 'Midnight Otaku Overshirt',
    category: 'Streetwear',
    price: 3499,
    originalPrice: 4599,
    stock: 14,
    rating: 4.9,
    reviews: 178,
    featured: true,
    bestseller: true,
    newArrival: true,
    collection: 'Tokyo Night',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'White'],
    description: 'Heavyweight anime-inspired overshirt with premium construction and a sharp minimal finish.',
    image: '/assets/images/prod-1.svg',
    gallery: ['/assets/images/prod-1.svg', '/assets/images/prod-2.svg'],
    tags: ['anime streetwear', 'oversized anime t-shirts']
  },
  {
    id: 2,
    slug: 'kyoto-ember-hoodie',
    name: 'Kyoto Ember Hoodie',
    category: 'Hoodies',
    price: 4299,
    originalPrice: 5299,
    stock: 9,
    rating: 4.8,
    reviews: 142,
    featured: true,
    bestseller: true,
    newArrival: true,
    collection: 'Urban Manga',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Orange'],
    description: 'Heavy fleece hoodie built for late-night marathons and everyday street layering.',
    image: '/assets/images/prod-2.svg',
    gallery: ['/assets/images/prod-2.svg', '/assets/images/prod-3.svg'],
    tags: ['anime hoodies', 'limited edition anime drops']
  },
  {
    id: 3,
    slug: 'hikari-figure-stand',
    name: 'Hikari Figure Stand',
    category: 'Collectibles',
    price: 2899,
    originalPrice: 3299,
    stock: 18,
    rating: 4.9,
    reviews: 134,
    featured: true,
    bestseller: false,
    newArrival: true,
    collection: 'Collector Vault',
    sizes: ['Standard'],
    colors: ['Black', 'White'],
    description: 'Collector-grade display stand with clean premium geometry and anime-inspired sculptural language.',
    image: '/assets/images/prod-3.svg',
    gallery: ['/assets/images/prod-3.svg', '/assets/images/prod-4.svg'],
    tags: ['manga collectibles', 'anime figures']
  },
  {
    id: 4,
    slug: 'neon-archive-poster',
    name: 'Neon Archive Poster',
    category: 'Posters',
    price: 1899,
    originalPrice: 2499,
    stock: 24,
    rating: 4.7,
    reviews: 98,
    featured: false,
    bestseller: false,
    newArrival: false,
    collection: 'Editorial Drops',
    sizes: ['A3', 'A2'],
    colors: ['Black', 'White'],
    description: 'Edition poster in monochrome and orange, designed for collector walls and creative spaces.',
    image: '/assets/images/prod-4.svg',
    gallery: ['/assets/images/prod-4.svg', '/assets/images/prod-5.svg'],
    tags: ['anime posters', 'anime gifts']
  },
  {
    id: 5,
    slug: 'tokyo-signal-keychain',
    name: 'Tokyo Signal Keychain',
    category: 'Accessories',
    price: 749,
    originalPrice: 999,
    stock: 42,
    rating: 4.8,
    reviews: 96,
    featured: false,
    bestseller: false,
    newArrival: true,
    collection: 'Daily Carry',
    sizes: ['One Size'],
    colors: ['Black', 'Orange'],
    description: 'Everyday metal keychain designed for daily carry and subtle anime-inspired brand expression.',
    image: '/assets/images/prod-5.svg',
    gallery: ['/assets/images/prod-5.svg', '/assets/images/prod-6.svg'],
    tags: ['anime accessories', 'anime keychains']
  },
  {
    id: 6,
    slug: 'harbor-tattoo-tee',
    name: 'Harbor Tattoo Tee',
    category: 'Streetwear',
    price: 2599,
    originalPrice: 3199,
    stock: 11,
    rating: 4.8,
    reviews: 212,
    featured: true,
    bestseller: true,
    newArrival: true,
    collection: 'Streetwear Essentials',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'White'],
    description: 'Minimalist graphic tee with premium cotton and a refined anime-inspired concept.',
    image: '/assets/images/prod-6.svg',
    gallery: ['/assets/images/prod-6.svg', '/assets/images/prod-1.svg'],
    tags: ['anime streetwear', 'Japanese streetwear']
  },
  {
    id: 7,
    slug: 'vanta-noir-bomber',
    name: 'Vanta Noir Bomber',
    category: 'Streetwear',
    price: 5399,
    originalPrice: 6499,
    stock: 8,
    rating: 4.9,
    reviews: 87,
    featured: true,
    bestseller: false,
    newArrival: false,
    collection: 'Urban Anime',
    sizes: ['M', 'L', 'XL'],
    colors: ['Black'],
    description: 'Archival bomber silhouette with premium detailing and a controlled monochrome finish.',
    image: '/assets/images/prod-7.svg',
    gallery: ['/assets/images/prod-7.svg', '/assets/images/prod-8.svg'],
    tags: ['anime streetwear', 'Japanese streetwear']
  },
  {
    id: 8,
    slug: 'samurai-static-mug',
    name: 'Samurai Static Mug',
    category: 'Accessories',
    price: 899,
    originalPrice: 1199,
    stock: 34,
    rating: 4.7,
    reviews: 76,
    featured: false,
    bestseller: false,
    newArrival: false,
    collection: 'Daily Ritual',
    sizes: ['Regular'],
    colors: ['Black', 'Orange'],
    description: 'Premium ceramic mug designed for studio sessions, coffee rituals, and desk setups.',
    image: '/assets/images/prod-8.svg',
    gallery: ['/assets/images/prod-8.svg', '/assets/images/prod-1.svg'],
    tags: ['anime accessories', 'anime gifts']
  }
];

const blogs = [
  {
    id: 1,
    title: 'Behind the Scenes of AKANESHI’s Tokyo-Inspired Drop',
    excerpt: 'A look into the design language, materials, and creative direction behind our latest collection.',
    category: 'Behind the Scenes',
    date: '2026-09-01',
    image: '/assets/images/blog-1.svg'
  },
  {
    id: 2,
    title: 'How to Style Anime Streetwear Without Losing Minimalism',
    excerpt: 'Balance your look with monochrome layers and purposeful orange accents for a premium finish.',
    category: 'Style Guide',
    date: '2026-09-12',
    image: '/assets/images/blog-2.svg'
  },
  {
    id: 3,
    title: 'Collector Essentials for a Premium Anime Room Setup',
    excerpt: 'Design ideas for a thoughtful collector environment shaped by streetwear, manga references, and product display.',
    category: 'Culture',
    date: '2026-09-20',
    image: '/assets/images/blog-3.svg'
  }
];

const testimonials = [
  { name: 'Priya S.', location: 'Mumbai', rating: 5, comment: 'The quality is premium, and the design language feels authentic without being overdone.' },
  { name: 'Rohit K.', location: 'Delhi', rating: 5, comment: 'Shipping was smooth and the hoodie feels like a premium collector piece.' },
  { name: 'Aanya M.', location: 'Bengaluru', rating: 5, comment: 'The finish and attention to detail feel premium. I would definitely order again.' }
];

const searchTrends = [
  'anime streetwear',
  'oversized anime t-shirts',
  'anime hoodies',
  'manga collectibles',
  'anime posters',
  'anime accessories',
  'Japanese streetwear',
  'anime gifts',
  'anime keychains',
  'anime figures',
  'manga merchandise',
  'limited edition anime drops'
];

module.exports = { products, blogs, testimonials, searchTrends };
